apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nodejs
  namespace: ENV
  labels:
        app: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 2 
  template: 
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: ikhsannugs/nodejs-backend:ENV-NO
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_HOST
          value: "149.129.248.62"
        - name: MONGODB_PORT
          value: "27017"
